/**
 * Description of a caption language track available on a YouTube video.
 */
export interface LanguageInfo {
  /** ISO 639‑1 or other language code provided by YouTube (e.g. 'en', 'fr') */
  code: string;
  /** Human readable name for the language (e.g. 'English', 'French') */
  name: string;
  /** Whether the captions were automatically generated (ASR) */
  autoGenerated: boolean;
  /** Whether this language is marked as the default track */
  isDefault: boolean;
  trackName?: string;
}

/**
 * A single transcript entry with start and end timestamps and the spoken text.
 */
export interface TranscriptEntry {
  /** Start time of the line in seconds */
  start: number;
  /** End time of the line in seconds */
  end: number;
  /** The caption text */
  text: string;
}

/**
 * Full transcript response returned by the transcript provider. Includes
 * metadata when available such as title, channel, thumbnail and duration.
 */
export interface TranscriptResponse {
  /** The canonical YouTube video ID */
  videoId: string;
  /** Optional video title */
  title?: string;
  /** Optional channel (author) name */
  channel?: string;
  /** Optional thumbnail URL (high quality default) */
  thumbnail?: string;
  /** Optional duration computed from transcript end times (seconds) */
  duration?: number;
  /** The actual transcript lines */
  transcript: TranscriptEntry[];
  /** List of available caption languages for the video */
  availableLanguages?: LanguageInfo[];
}

/**
 * Interface implemented by services capable of fetching transcripts for
 * YouTube videos. Multiple concrete providers can implement this to allow
 * swapping out the underlying caption source (e.g. YouTube captions,
 * speech‑to‑text, third‑party APIs).
 */
export interface TranscriptProvider {
  /**
   * Fetches the transcript for a given video. If the requested language is not
   * available the provider should choose a reasonable default or throw an
   * error. The response must include the videoId and transcript entries and
   * may include other metadata as available.
   *
   * @param videoId The YouTube video identifier
   * @param lang Optional language code to fetch
   */
  getTranscript(videoId: string, lang?: string): Promise<TranscriptResponse>;
}