import { POST } from '@/app/api/transcript/route';

// Mock the transcript provider
jest.mock('@/lib/providers/youtubeProvider', () => {
  return {
    youtubeTranscriptProvider: {
      getTranscript: jest.fn().mockResolvedValue({
        videoId: 'abc123def45',
        title: 'Test Title',
        channel: 'Test Channel',
        thumbnail: 'http://example.com/thumb.jpg',
        duration: 5,
        transcript: [
          { start: 0, end: 2, text: 'Hello world' },
          { start: 2, end: 5, text: 'This is a test' },
        ],
        availableLanguages: [
          { code: 'en', name: 'English', autoGenerated: false, isDefault: true },
        ],
      }),
    },
  };
});

describe('POST /api/transcript', () => {
  it('returns 400 when url is missing', async () => {
    const req = new Request('http://localhost/api/transcript', {
      method: 'POST',
      body: JSON.stringify({}),
      headers: { 'Content-Type': 'application/json' },
    });
    const res = (await POST(req)) as Response;
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toBeDefined();
  });

  it('returns transcript data when given a valid URL', async () => {
    const req = new Request('http://localhost/api/transcript', {
      method: 'POST',
      body: JSON.stringify({ url: 'https://youtu.be/abc123def45' }),
      headers: { 'Content-Type': 'application/json' },
    });
    const res = (await POST(req)) as Response;
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.videoId).toBe('abc123def45');
    expect(body.transcript).toHaveLength(2);
    expect(body.title).toBe('Test Title');
  });
});