import { YoutubeTranscriptProvider } from '@/lib/providers/youtubeProvider';

// Jest automatically hoists jest.mock calls; we place the mock at top level to
// intercept the dynamic import of youtube-caption-extractor in the provider.
jest.mock('youtube-caption-extractor', () => {
  return {
    getSubtitles: jest.fn().mockResolvedValue([
      { start: '0', dur: '2', text: 'Hello world' },
      { start: '2', dur: '3', text: 'This is a test' },
    ]),
    getVideoDetails: jest.fn().mockResolvedValue({ title: 'Mock Video Title' }),
  };
});

describe('YoutubeTranscriptProvider', () => {
  const originalFetch = global.fetch;

  beforeEach(() => {
    // Mock global fetch
    global.fetch = jest.fn().mockImplementation((url: string) => {
      if (url.includes('timedtext?type=list')) {
        // Return a simple language list with English as default and French auto
        const xml =
          '<track lang_code="en" lang_translated="English" lang_default="true" />' +
          '<track lang_code="fr" lang_translated="French" kind="asr" />';
        return Promise.resolve({ ok: true, text: () => Promise.resolve(xml) } as any);
      }
      if (url.includes('oembed')) {
        return Promise.resolve({
          ok: true,
          json: () =>
            Promise.resolve({
              title: 'OEmbed Video Title',
              author_name: 'Test Channel',
              thumbnail_url: 'http://example.com/thumb.jpg',
            }),
        } as any);
      }
      // Fallback for timedtext JSON – return empty events (not used in this test)
      if (url.includes('timedtext') && url.includes('fmt=json3')) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve({ events: [] }) } as any);
      }
      return Promise.resolve({ ok: true, text: () => Promise.resolve('') } as any);
    });
  });

  afterEach(() => {
    global.fetch = originalFetch;
    jest.resetModules();
    jest.clearAllMocks();
  });

  it('returns transcript using the extractor and oEmbed metadata', async () => {
    const provider = new YoutubeTranscriptProvider();
    const result = await provider.getTranscript('abc123def45', 'en');
    // Expect transcript lines to match mocked subtitles
    expect(result.transcript).toHaveLength(2);
    expect(result.transcript[0]).toMatchObject({ start: 0, end: 2, text: 'Hello world' });
    expect(result.transcript[1]).toMatchObject({ start: 2, end: 5, text: 'This is a test' });
    // Expect metadata to come from mock and oembed
    expect(result.title).toBe('Mock Video Title');
    expect(result.channel).toBe('Test Channel');
    expect(result.thumbnail).toBe('http://example.com/thumb.jpg');
    expect(result.availableLanguages).toEqual([
      { code: 'en', name: 'English', autoGenerated: false, isDefault: true },
      { code: 'fr', name: 'French', autoGenerated: true, isDefault: false },
    ]);
  });
});