"use client";
import type { LanguageInfo } from '@/lib/transcriptProvider';

interface LanguageSelectorProps {
  languages: LanguageInfo[];
  selected: string;
  onSelect: (code: string) => void;
}

/**
 * Dropdown for selecting a caption language. Shows the language name and
 * indicates when a track is auto‑generated. The default track is marked.
 */
export default function LanguageSelector({ languages, selected, onSelect }: LanguageSelectorProps) {
  if (!languages || languages.length === 0) return null;
  return (
    <div className="mt-4">
      <label htmlFor="lang" className="mr-2 font-medium">
        Language:
      </label>
      <select
        id="lang"
        value={selected}
        onChange={(e) => onSelect(e.target.value)}
        className="p-2 border rounded"
      >
        {languages.map((lang) => (
          <option key={lang.code} value={lang.code}>
            {lang.name}
            {lang.autoGenerated ? ' (auto)' : ''}
            {lang.isDefault ? ' (default)' : ''}
          </option>
        ))}
      </select>
    </div>
  );
}