import type {
  TranscriptProvider,
  TranscriptEntry,
  TranscriptResponse,
  LanguageInfo,
} from '../transcriptProvider';

/**
 * Fetches available caption tracks for a YouTube video using the legacy
 * timedtext list endpoint. It returns an array of languages with human
 * readable names and flags indicating whether each track is auto‑generated or
 * default. If the endpoint cannot be reached or returns invalid data the
 * result will be an empty array.
 *
 * @param videoId YouTube video identifier
 */
async function fetchAvailableLanguages(videoId: string): Promise<LanguageInfo[]> {
  try {
    const res = await fetch(
      `https://www.youtube.com/api/timedtext?type=list&v=${encodeURIComponent(videoId)}`
    );
    if (!res.ok) {
      return [];
    }
    const xml = await res.text();
    const matches = [...xml.matchAll(/<track\b[^>]+>/g)];
    return matches.map((m) => {
      const trackTag = m[0];
      const attrs: Record<string, string> = {};
      trackTag.replace(/(\w+)="([^"]*)"/g, (_, name: string, value: string) => {
        attrs[name] = value;
        return '';
      });
      return {
        code: attrs.lang_code,
        name: attrs.lang_translated ?? attrs.lang_code,
        autoGenerated: attrs.kind === 'asr',
        isDefault: attrs.lang_default === 'true',
        trackName: attrs.name || "",
      } as LanguageInfo;
    });
  } catch (err) {
    return [];
  }
}

/**
 * Fetches transcript events from the YouTube timedtext API in JSON3 format.
 * Returns an array of transcript entries with start/end timestamps and text.
 *
 * @param videoId YouTube video identifier
 * @param lang Language code for captions
 */
async function fetchTranscriptFromTimedtext(
  videoId: string,
  lang: string,
  trackName: string = '',
  autoGenerated: boolean = false
): Promise<TranscriptEntry[]> {
  try {
    let baseUrl = `https://www.youtube.com/api/timedtext?v=${encodeURIComponent(
      videoId
    )}&lang=${encodeURIComponent(lang)}&fmt=json3`;

    if (trackName) {
      baseUrl += `&name=${encodeURIComponent(trackName)}`;
    }
    if (autoGenerated) {
      baseUrl += `&kind=asr`;
    }

    // 1️⃣ Try fetching with the constructed URL
    let res = await fetch(baseUrl);
    if (!res.ok) {
      // If the specific track fails and we didn't force ASR, maybe try fallback?
      // But for now, let's stick to the requested logic.
      return [];
    }

    let data = await res.json();

    // 2️⃣ If no events, and we haven't already forced ASR, retry with auto-generated captions (kind=asr)
    // ONLY if the original request wasn't already for ASR.
    if ((!data?.events || data.events.length === 0) && !autoGenerated) {
      const asrRes = await fetch(`${baseUrl}&kind=asr`);
      if (asrRes.ok) {
        data = await asrRes.json();
      }
    }

    const events: any[] = data?.events || [];
    const transcript: TranscriptEntry[] = [];

    for (let i = 0; i < events.length; i++) {
      const ev = events[i];
      if (!ev.segs) continue;

      const text = (ev.segs as any[])
        .map((seg) => seg.utf8)
        .join("")
        .replace(/\n+/g, " ")
        .trim();

      if (!text) continue;

      const start =
        typeof ev.tStartMs === "number" ? ev.tStartMs / 1000 : 0;

      let dur = 0;
      if (typeof ev.dDurationMs === "number") {
        dur = ev.dDurationMs / 1000;
      } else if (
        i + 1 < events.length &&
        typeof events[i + 1].tStartMs === "number"
      ) {
        dur = (events[i + 1].tStartMs - ev.tStartMs) / 1000;
      }

      const end = start + dur;

      transcript.push({
        start,
        end,
        text,
      });
    }

    return transcript;
  } catch (err) {
    console.error("Timedtext fetch failed:", err);
    return [];
  }
}
/**
 * Fetches basic video metadata via YouTube's oEmbed endpoint. This endpoint
 * returns JSON containing the video title, author and thumbnail URL and does
 * not require an API key. If any fields are missing the corresponding
 * property will be undefined.
 *
 * @param videoId YouTube video identifier
 */
async function fetchVideoMetadata(videoId: string): Promise<{
  title?: string;
  channel?: string;
  thumbnail?: string;
}> {
  try {
    const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${encodeURIComponent(
      videoId
    )}&format=json`;
    const res = await fetch(oembedUrl);
    if (!res.ok) {
      return {};
    }
    const data = await res.json();
    return {
      title: data.title,
      channel: data.author_name,
      thumbnail: data.thumbnail_url,
    };
  } catch (err) {
    return {};
  }
}

/**
 * Concrete transcript provider that uses YouTube's caption APIs and
 * `youtube-caption-extractor` as a primary source. The extractor is
 * leveraged when available to handle YouTube's engagement API and other
 * undocumented endpoints for improved reliability【930633602005964†L0-L6】. If the
 * extractor fails or is not installed the provider falls back to the
 * timedtext API which is supported without authentication.
 */
export class YoutubeTranscriptProvider implements TranscriptProvider {
  async getTranscript(videoId: string, lang?: string): Promise<TranscriptResponse> {
    // Determine available languages first to honour defaults
    const available = await fetchAvailableLanguages(videoId);
    const chosenLang =
      lang || available.find((l) => l.isDefault)?.code || available[0]?.code || 'en';

    let transcript: TranscriptEntry[] = [];
    let title: string | undefined;
    let channel: string | undefined;
    let thumbnail: string | undefined;

    // Attempt to use youtube-caption-extractor if it's installed
    try {
      // eslint-disable-next-line no-undef
      const extractor = await import('youtube-caption-extractor');
      if (extractor.getSubtitles) {
        const subtitles = await extractor
          .getSubtitles({ videoID: videoId, lang: chosenLang })
          .catch(() => null);
        if (Array.isArray(subtitles)) {
          transcript = subtitles.map((s: any) => ({
            start: parseFloat(s.start),
            end: parseFloat(s.start) + parseFloat(s.dur),
            text: s.text,
          }));
        }
      }
      if (extractor.getVideoDetails) {
        const details = await extractor
          .getVideoDetails({ videoID: videoId, lang: chosenLang })
          .catch(() => null);
        if (details) {
          title = details.title;
          // The API does not currently expose channel or thumbnail; fallback later
        }
      }
    } catch (err) {
      // Ignored: extractor not available or failed
    }

    // Fallback to timedtext if no transcript found
    if (transcript.length === 0) {
      const chosen =
        available.find((l) => l.code === chosenLang) ||
        available.find((l) => l.isDefault) ||
        available[0];

      if (chosen) {
        transcript = await fetchTranscriptFromTimedtext(
          videoId,
          chosen.code,
          chosen.trackName,
          chosen.autoGenerated
        );
      } else {
        transcript = [];
      }
    }

    // Fetch metadata if any field missing
    const meta = await fetchVideoMetadata(videoId);
    if (!title) title = meta.title;
    if (!channel) channel = meta.channel;
    if (!thumbnail) thumbnail = meta.thumbnail;

    // Compute duration as the end of the last caption
    const duration = transcript.length ? transcript[transcript.length - 1].end : undefined;

    return {
      videoId,
      title,
      channel,
      thumbnail,
      duration,
      transcript,
      availableLanguages: available,
    };
  }
}

// Export a singleton instance for convenience
export const youtubeTranscriptProvider = new YoutubeTranscriptProvider();